#!/usr/bin/env python
# copyright Jeremy Large 2020

import argparse
import logging

from rube.data.uci_files import load_uci_file, REMOTE_FILE, SHEET_NAME, UCI_DATA_DIR

# create logger
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG)


TEST_DATALENGTH = 10000000


parser = argparse.ArgumentParser()

parser.add_argument("--in_file", type=str, default=REMOTE_FILE,
                    help="path to the excel file containing the data")

parser.add_argument("--excel_sheet", type=str, default=SHEET_NAME,
                    help="the tab in --excel_infile to consult")

parser.add_argument("--n_lines", type=int, default=TEST_DATALENGTH,
                    help="the number of lines in the file to parse")

args = parser.parse_args()

n_lines = args.n_lines
if __name__ == '__main__':
    df = load_uci_file(args.in_file, args.excel_sheet)
    if not UCI_DATA_DIR.exists():
        UCI_DATA_DIR.mkdir()
    df.loc[:args.n_lines].to_csv(UCI_DATA_DIR / "uci_raw.csv")
    logging.info('Saving the first ' + str(n_lines) + ' lines to ' + str(UCI_DATA_DIR))
